- name: Deploy a web application
  hosts: db_and_web_server

- import_tasks: solution_python_tasks.yml

- import_tasks: flask_web_tasks.yml

# # 
#     - name: Install Python Flask dependencies
#       pip:
#         name: '{{ item }}'
#         state: present
#       with_items:
#        - flask
#        - flask-mysql

#     - name: Copy web-server code
#       copy: src=app.py dest=/opt/app.py

#     - name: Start web-application
#       shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &

## IF DIVIDED BY ROLES
  # name: Deploy a web application
  # hosts: db_and_web_server
  # roles:
  #   - python
  #   - mysql_db
  #   - flask_web